$background = 040304
$onBackground = f1e1eb
$surface = 040304
$surfaceDim = 040304
$surfaceBright = 110b0f
$surfaceContainerLowest = 000000
$surfaceContainerLow = 070406
$surfaceContainer = 090509
$surfaceContainerHigh = 0c070b
$surfaceContainerHighest = 0f090e
$onSurface = f1e1eb
$surfaceVariant = 0f090e
$onSurfaceVariant = b6a7b0
$outline = 7e727a
$outlineVariant = 50454c
$inverseSurface = fff7f9
$inverseOnSurface = 5a5357
$shadow = 000000
$scrim = 000000
$surfaceTint = 32232f
$primary = e6b9dc
$primaryDim = d7acce
$onPrimary = 563551
$primaryContainer = 6a4764
$onPrimaryContainer = ffd8f5
$inversePrimary = 775371
$primaryFixed = fdcff3
$primaryFixedDim = efc1e4
$onPrimaryFixed = 51314d
$onPrimaryFixedVariant = 704c6a
$secondary = dabfd2
$secondaryDim = ccb1c4
$onSecondary = 4e3a4a
$secondaryContainer = 493545
$onSecondaryContainer = d3b7cb
$secondaryFixed = f7daef
$secondaryFixedDim = e9cce0
$onSecondaryFixed = 4d3949
$onSecondaryFixedVariant = 6b5566
$tertiary = ebdcff
$tertiaryDim = dfccfd
$onTertiary = 594b74
$tertiaryContainer = dfccfd
$onTertiaryContainer = 50426a
$tertiaryFixed = dfccfd
$tertiaryFixedDim = d1beee
$onTertiaryFixed = 3d2f56
$onTertiaryFixedVariant = 5a4b74
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 916b8a
$secondaryPaletteKeyColor = 877082
$tertiaryPaletteKeyColor = 80709b
$neutralPaletteKeyColor = 7d7579
$neutralVariantPaletteKeyColor = 80737b
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 916b8a
$secondary_paletteKeyColor = 877082
$tertiary_paletteKeyColor = 80709b
$neutral_paletteKeyColor = 7d7579
$neutral_variant_paletteKeyColor = 80737b
$term0 = 080808
$term1 = f647c6
$term2 = ffbac2
$term3 = ffdde7
$term4 = b3a2d5
$term5 = dc93ca
$term6 = ffba93
$term7 = ebd2d9
$term8 = b19ea4
$term9 = ff79d1
$term10 = ffd2d5
$term11 = fff1f3
$term12 = babfdd
$term13 = edabd8
$term14 = ffd1c0
$term15 = ffffff
$rosewater = feedf3
$flamingo = f7dae9
$pink = ffcef4
$mauve = eea9ee
$red = ee98d6
$maroon = e8add3
$peach = febada
$yellow = ffedf0
$green = ffd8c5
$teal = dedcff
$sky = ead2ff
$sapphire = e2b7ff
$blue = e0a8f4
$lavender = eebbf7
$klink = a573c1
$klinkSelection = a673c1
$kvisited = b561b4
$kvisitedSelection = b561b4
$knegative = db52b7
$knegativeSelection = db52b7
$kneutral = ff7fc6
$kneutralSelection = ff7fc6
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f1e1eb
$subtext1 = b6a7b0
$subtext0 = 7e727a
$overlay2 = 191819
$overlay1 = 171616
$overlay0 = 141213
$surface2 = 100f10
$surface1 = 0c0a0b
$surface0 = 050405
$base = 010001
$mantle = 010001
$crust = 010001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
