exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(D9B9FFff) rgba(615372ff) 45deg
    col.inactive_border = rgba(030205ff) rgba(2F2061ff) 45deg
}

group {
    col.border_active = rgba(D9B9FFFF) rgba(615372FF) 45deg
    col.border_inactive = rgba(D9B9FFCC) rgba(615372CC) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(B0B5ABff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
