general {
    lock_cmd = qs -c caelestia ipc call lock lock
    unlock_cmd = qs -c caelestia ipc call lock unlock
}

listener {
    timeout = 900
    on-timeout = qs -c caelestia ipc call lock lock
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
