general {
    lock_cmd = noctalia msg session lock
    unlock_cmd = noctalia msg session lock
}

listener {
    timeout = 900
    on-timeout = noctalia msg session lock
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1500
    on-timeout = systemctl suspend
}
