-- Generated by nwg-displays on 2026-07-06 at 22:36:04. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.06",
    position = "3072x0",
    scale = 1.25
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1536x0",
    scale = 1.25
})
