
[urgency_low]
    background = "#A3766580"
    foreground = "#FFDACCE6"
    frame_color = "#A3766503"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#523A6B80"
    foreground = "#E6CCFFE6"
    frame_color = "#523A6B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
