foreground              #FFFFFF
background              #030205
selection_foreground    #030205
selection_background    #FFFFFF
cursor                  #9E66DD 
cursor_text_color       #B0B5AB

active_tab_foreground     #030205
active_tab_background     #58419D
inactive_tab_foreground   #58419D
inactive_tab_background   #030205

# black
color0      #362952
color8      #6A578F

# red
color1      #E4CCFF
color9      #CBAAF0

# green
color2      #D8CCFF
color10     #BAAAF0

# yellow
color3      #D9CCFF
color11     #BCAAF0

# blue
color4      #B39AE6
color12     #B39AE6

# magenta
color5      #AB9AE6
color13     #AB9AE6

# cyan
color6      #AD9AE6
color14     #AD9AE6

# white
color7      #E4CCFF
color15     #CBAAF0
